# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - pys

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Create Virtual Environment
      run: |
        python -m venv env
    
    - name: Activate Virtual Environment
      run: |
        .\env\Scripts\activate
    
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install reqirements
      run: |
        pip install -r requirements.txt

    - name: Zip the application files
      run: Compress-Archive .\* app.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pys'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1934de5aee474f1c94960352171a2ab2 }}
        package: '.\app.zip'
